version: 0.0
os: windows
files:
  - source: \aws
    destination: C:\temp\codedeployresources
hooks:
  BeforeInstall:
    - location: aws\scripts\before-install.ps1
      timeout: 300
      runas: root
  AfterInstall:
    - location: aws\scripts\after-install.ps1
      timeout: 300
      runas: root