name: Build and Deploy .NET Framework 4.7 Application


on:
  push:
    branches: [ main ]
  pull_request:

env:
  applicationfolder: dotnet_legacy-master
  AWS_REGION: us-east-1
  S3BUCKET: codedeploystack-webappdeploymentbucket-1644x54in5q6g
  ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'


jobs:
  build:
    name: Build and Package
    runs-on: windows-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repository
      
            

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
          # aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-session-name: GitHub-Action-Role
          aws-region: ${{ env.AWS_REGION }}

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1
      
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2
       
      - name: Restore NuGet Packages
        working-directory: ${{ env.applicationfolder }}
        run: nuget restore WebApplication3.sln

      - name: Build and Package .NET Framework
        
        working-directory: ${{ env.applicationfolder }}
        # run : msbuild /p:Configuration=Release
        run: msbuild Webapplication3.sln /p:Configuration=Release /p:DeployOnBuild=True /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:publishUrl=\bin\Release\Publish
        
      - name: Zip files
        working-directory: ${{ env.applicationfolder }}
        run: Compress-Archive -Path \bin\Release\Publish\* -Destination deployment.zip
        # run: Compress-Archive -Path \bin\Release\Publish\* -DestinationPath \bin\Release\Publish\sample.zip
  
      - name: Update S3 client to use crt
        run: aws configure set default.s3.preferred_transfer_client crt
      
      - name: Upload Artifact to S3
        working-directory: ${{ env.applicationfolder }}
        run: aws s3 cp deployment.zip s3://${{ env.S3BUCKET }}/
        # run: aws s3 cp \bin\Release\Publish\sample.zip s3://${{ env.S3BUCKET }}/deployment/sample.zip
      
      
    


  deploy:
    needs: build
    runs-on: ubuntu-latest
    # environment: Dev
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v2
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
        # aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        # aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        role-session-name: GitHub-Action-Role
        aws-region: ${{ env.AWS_REGION }}
      # noqa: runtime-reference GITHUB_REF_SLUG
    - run: |                                             
        echo "Deploying branch ${{ env.GITHUB_REF }} to ${{ github.event.inputs.environment }}
        commit_hash=`git rev-parse HEAD`
        aws deploy create-deployment --application-name CodeDeployAppNameWithASG --deployment-group-name CodeDeployGroupName --github-location repository=$GITHUB_REPOSITORY,commitId=$commit_hash --ignore-application-stop-failures
    
  # aws deploy create-deployment --application-name CodeDeployAppNameWithASG --deployment-group-name CodeDeployGroupName --s3-location bucket=${{ env.S3BUCKET }},key=deployment/sample.zip,bundleType=zip
      # aws deploy create-deployment --application-name CodeDeployAppNameWithASG --deployment-group-name CodeDeployGroupName --github-location repository=$GITHUB_REPOSITORY,commitId=$commit_hash --ignore-application-stop-failures
        